### ISSUE TITLE
Edit the README.md file to reflect our example use cases so far

### ISSUE THREAD

**Issue by agstephens** [cedadev/checksit#14]
- [x] look at `cli_tests.txt`
- [x] for each test run:
  - [x] write some text to explain what it does
  - [x] include the example in a code block
- [ ] maybe write additional sections for things that we need to add
- [ ] review issues in the "To Document" column and make sure they are reflected in the examples in the README

**Comment by joshua-hampton** [comment]
In progress, within `specs-fmt-checks-etc-hampton` branch.
Current progress in README
* each of the main 4 sections of checksit has a description (some more full than others)
* each flag (particularly within `checksit check`) has a description with an example

**Comment by joshua-hampton** [comment]
Marking as closed due to changes in README and additional documentation
