### ISSUE TITLE
Image reading and checking

### ISSUE THREAD

**Issue by joshua-hampton** [cedadev/checksit#24]
Started a new branch [ncas-image](https://github.com/cedadev/checksit/tree/ncas-image) to start work on compliance checking images, thinking in particular of the NCAS-IMAGE standard.
Started on [reader script](https://github.com/cedadev/checksit/blob/ncas-image/checksit/readers/image.py) that uses [exiftool](https://exiftool.org) to read image metadata, returns all as global attributes.

- [x] create a list of ncas-image standard attributes to check against
- [x] check for attributes to have correct label in the metadata as per the standard (correctly cased, spelling)
- [x] determine what types of checks to use for each attribute based on the available list of 'rules' in checksit and available option(s) for the rule
- [x] write yaml file under specs folder for global attributes
- [x] if differences are identified between data product types for a given attribute add these into available data product yaml spec files

**Comment by Shanrahan16** [comment]
Warnings code has been written, I just need to go through and change the yaml file so that certain fields give warnings not errors (as they do currently) e.g. warning if not a CEDA catalogue link in "Relation" (as a DOI link would be acceptable in some cases)

**Comment by Shanrahan16** [comment]
> I have yet to add valid url checks (as in to check if the website actually exists on the internet).

Complete

**Comment by joshua-hampton** [comment]
Does that mean that the user must be connected to the internet for this to work? For example, if someone's on campaign in the middle of nowhere, adding correct metadata on the fly and checking their files with this as they go, what message would they get?

**Comment by Shanrahan16** [comment]
> Warnings code has been written, I just need to go through and change the yaml file so that certain fields give warnings not errors (as they do currently) e.g. warning if not a CEDA catalogue link in "Relation" (as a DOI link would be acceptable in some cases).

Complete

**Comment by Shanrahan16** [comment]
> Does that mean that the user must be connected to the internet for this to work? For example, if someone's on campaign in the middle of nowhere, adding correct metadata on the fly and checking their files with this as they go, what message would they get?

We're only giving a warning for URL checks rather than an error, as URLs may not be live all the time.

**Comment by Shanrahan16** [comment]
Link to spreadsheet of checks implemented: https://docs.google.com/spreadsheets/d/1VnMpprRwG8G3B4uv1MdBG-hSZ_5LklTJv0e61jUenUg/edit#gid=2140455130

**Comment by Shanrahan16** [comment]
I have noticed that in amof-global-attrs.yml (NCAS General Standard), `platform_altitude: regex:^\d+\.?\d*\sm$` does not allow negative values?

**Comment by joshua-hampton** [comment]
Closing this issue as version 1.0 of NCAS Image is in checksit
