### ISSUE TITLE
Platform altitude does not allow negative values

### ISSUE THREAD

**Issue by Shanrahan16** [cedadev/checksit#37]
* checksit version: ncas-image branch
* Python version:
* Operating System:

### Description

I have noticed that in amof-global-attrs.yml (NCAS General Standard), `platform_altitude: regex:^\d+\.?\d*\sm$` does not allow negative values?

**Comment by joshua-hampton** [comment]
Fixed in commit https://github.com/cedadev/checksit/pull/30/commits/1f2bf7d6a224c233d7c30e393580416a99c79c4a, included in PR #30
